version: '2'
services:
    nimbus:
        tty: true
        command: nimbus
        image: registry.locman.cn/sefon-public/alpine-storm:1.1.2
        ports:
            - "3773:3773"
            - "3772:3772"
            - "6627:6627"
        external_links:
            - ${zk_link}:zk
        environment:
            - JVMFLAGS=-Xmx${storm_mem}m -Xms${storm_mem}m
            - env=${storm_env}
            - ZK_SERVICE=${zk_link}
    
    supervisor:
        tty: true
        command: supervisor logviewer
        image: registry.locman.cn/sefon-public/alpine-storm:1.1.2
        ports:
            - "8000:8000"
            - "6700:6700"
            - "6701:6701"
            - "6702:6702"
            - "6703:6703"
        links:
            - nimbus:nimbus
        external_links:
            - ${zk_link}:zk
        environment:
            - JVMFLAGS=-Xmx${storm_mem}m -Xms${storm_mem}m
            - env=${storm_env}
            - ZK_SERVICE=${zk_link}
        depends_on:
            - nimbus

    ui:
        tty: true
        command: ui
        image: registry.locman.cn/sefon-public/alpine-storm:1.1.2
        ports:
            - "8080:8080"
        links:
            - nimbus:nimbus
        external_links:
            - ${zk_link}:zk
        environment:
            - JVMFLAGS=-Xmx${storm_mem}m -Xms${storm_mem}m
            - env=${storm_env}
            - ZK_SERVICE=${zk_link}
        depends_on:
            - nimbus
            - supervisor
