version: '2'
services:
    nimbus:
        tty: true
        command: --daemon nimbus logviewer
        image: registry.locman.cn/sefon-public/alpine-storm:1.1.2
        ports:
            - "8081:8081"
        external_links:
            - ${zk_link}:zk
        environment:
            - env=${storm_env}
            - ZK_SERVICE=${zk_link}
            - JVM_OPTS=-Xmx${storm_mem}m -Xms${storm_mem}m

    supervisor:
        tty: true
        command: --daemon supervisor logviewer
        image: registry.locman.cn/sefon-public/alpine-storm:1.1.2
        ports:
            - "8081:8081"
        external_links:
            - ${zk_link}:zk
        environment:
            - env=${storm_env}
            - ZK_SERVICE=${zk_link}
            - JVM_OPTS=-Xmx${storm_mem}m -Xms${storm_mem}m
        depends_on:
            - nimbus

    ui:
        tty: true
        command: --daemon ui
        image: registry.locman.cn/sefon-public/alpine-storm:1.1.2
        ports:
            - "8080:8080"
        external_links:
            - ${zk_link}:zk
        environment:
            - env=${storm_env}
            - ZK_SERVICE=${zk_link}
            - JVM_OPTS=-Xmx${storm_mem}m -Xms${storm_mem}m
        depends_on:
            - nimbus
            - supervisor
