.catalog:
  name: Storm
  version: 1.1.2-rancher1
  description: |
    (Experimental) Apache Storm cluster.
  minimum_rancher_version: v0.56.0
  maintainer: "RichieMay <meibo@sefon.com>"
  uuid: storm-0
  questions:
    - variable: "nimbus_scale"
      description: "Number of nimbus nodes."
      label: "Nimbus Nodes:"
      required: true
      default: 1
      type: "int"
    - variable: "supervisor_scale"
      description: "Number of supervisor nodes."
      label: "Supervisor Nodes:"
      required: true
      default: 3
      type: "int"
    - variable: "ui_scale"
      description: "Number of ui nodes."
      label: "UI Nodes:"
      required: true
      default: 1
      type: "int"
    - variable: "zk_link"
      description: |
        Choose the Zookeeper service to use. 
        It's really recommended a dedicated zookeeper service just for Storm.
      label: "Zookeeper stack/service"
      default: "storm-zk/zk"
      required: true
      type: "service"
