.catalog:
  name: Storm
  version: 1.1.2-rancher1
  description: |
    (Experimental) Apache Storm cluster.
  minimum_rancher_version: v0.56.0
  maintainer: "RichieMay <meibo@sefon.com>"
  uuid: storm-0
  questions:
    - variable: "storm_env"
      description: "Environment of apollo config."
      label: "Storm Environment:"
      required: true
      type: "enum"
      options: # List of options if using type of `enum`
        - DEV
        - FAT 
        - UAT
        - PRO
    - variable: "storm_mem"
      description: "Amount of memory to config storm worker process."
      label: "JVM Memory(MB):"
      required: true
      default: 1024
      type: "int"
    - variable: "storm_data_dir"
      description: "Directory where storm store data."
      label: "Storm data dir:"
      required: true
      default: "/opt/storm/data"
      type: "string"
    - variable: "nimbus_scale"
      description: "Number of nimbus nodes."
      label: "Nimbus Nodes:"
      required: true
      default: 1
      type: "int"
    - variable: "supervisor_scale"
      description: "Number of supervisor nodes."
      label: "Supervisor Nodes:"
      required: true
      default: 3
      type: "int"
    - variable: "ui_scale"
      description: "Number of ui nodes."
      label: "UI Nodes:"
      required: true
      default: 1
      type: "int"
    - variable: "zk_link"
      description: |
        Choose the Zookeeper service to use. 
        It's really recommended a dedicated zookeeper service just for Storm.
      label: "Zookeeper stack/service"
      default: "zookeeper/zk"
      required: true
      type: "service"
nimbus:
  scale: ${nimbus_scale}
  health_check:
    port: 6627
    interval: 15000
    unhealthy_threshold: 3
    request_line: ''
    healthy_threshold: 2
    response_timeout: 5000
ui:
  scale: ${ui_scale}
  health_check:
    port: 8080
    interval: 10000
    unhealthy_threshold: 3
    request_line: ''
    healthy_threshold: 2
    response_timeout: 5000
