.catalog:
  name: Storm
  version: 1.1.2-rancher1
  description: |
    (Experimental) Apache Storm cluster.
  minimum_rancher_version: v0.56.0
  maintainer: "RichieMay <meibo@sefon.com>"
  uuid: storm-0
  questions:
    - variable: "storm_env"
      description: "Environment of Apollo Config."
      label: "Storm Environment:"
      required: true
      default: |
      type: "enum"
      options: # List of options if using type of `enum`
        - Option DEV
        - Option FAT 
        - Option UAT
        - Option PRO
        
    - variable: "storm_mem"
      description: "Amount of memory to config storm."
      label: "JVM Memory (mb):"
      required: true
      default: 1024
      type: "int"
    - variable: "nimbus_scale"
      description: "Number of nimbus nodes."
      label: "Nimbus Nodes:"
      required: true
      default: 1
      type: "int"
    - variable: "supervisor_scale"
      description: "Number of supervisor nodes."
      label: "Supervisor Nodes:"
      required: true
      default: 3
      type: "int"
    - variable: "ui_scale"
      description: "Number of ui nodes."
      label: "UI Nodes:"
      required: true
      default: 1
      type: "int"
    - variable: "zk_link"
      description: |
        Choose the Zookeeper service to use. 
        It's really recommended a dedicated zookeeper service just for Storm.
      label: "Zookeeper stack/service"
      default: "storm-zk/zk"
      required: true
      type: "service"
nimbus:
  scale: ${nimbus_scale}
  health_check:
    port: 6627
    interval: 5000
    unhealthy_threshold: 3
    request_line: ''
    healthy_threshold: 2
    response_timeout: 5000
supervisor:
  scale: ${supervisor_scale}
  health_check:
    port: 6700
    interval: 10000
    unhealthy_threshold: 3
    request_line: ''
    healthy_threshold: 2
    response_timeout: 5000
ui:
  scale: ${ui_scale}
  health_check:
    port: 8080
    interval: 60000
    unhealthy_threshold: 3
    request_line: ''
    healthy_threshold: 2
    response_timeout: 10000
