version: '2'
services:
    pusher:
        tty: true
        command: pusher
        image: registry.locman.cn/sefon-public/alpine-topology:1.1.2
        environment:
            - KAFKA_SERVICE=${kafka_link}
        labels:
            io.rancher.container.start_once: true

    controller:
        tty: true
        command: controller
        image: registry.locman.cn/sefon-public/alpine-topology:1.1.2
        environment:
            - KAFKA_SERVICE=${kafka_link}
        labels:
            io.rancher.container.start_once: true