name: Kafka Connector
description: |
  Kafka Connector
version: 1.1.2-rancher1
category: Clustering
maintainer: "RichieMay <meibo@sefon.com>"
minimum_rancher_version: v0.59.0
license: 
projectURL: https://github.com/RichieMay/rancher-catalog